### ISSUE TITLE
Make bash script for just running align and analyze

### ISSUE THREAD

**Issue by lthealy** [SBU-BMI/til_align#11]
should be primarily compatible with older output formats, as newer format will automatically skip inference if files exist for all images

**Comment by kaczmarj** [comment]
i made the script in but when i run it, i get an error in the til-align pipeline.

```
```

**Comment by kaczmarj** [comment]
here's a subset of the files in the `data` dir:

```
data/
├── dl.sh
├── results-tilalign
├── results-tils
│   ├── prediction-TCGA-3C-AALI-01Z-00-DX1.F6E9A5DF-D8FB-45CF-B4BD-C6B76294C291
│   ├── prediction-TCGA-3C-AALJ-01Z-00-DX1.777C0957-255A-42F0-9EEB-A3606BCF0C96
│   └── prediction-TCGA-3C-AALK-01Z-00-DX1.4E6EB156-BB19-410F-878F-FC0EA7BD0B53
└── results-tumor
    ├── prediction-TCGA-3C-AALI-01Z-00-DX1
    ├── prediction-TCGA-3C-AALI-01Z-00-DX2
    ├── prediction-TCGA-3C-AALJ-01Z-00-DX1
    ├── prediction-TCGA-3C-AALJ-01Z-00-DX2
    └── prediction-TCGA-3C-AALK-01Z-00-DX1
```

**Comment by lthealy** [comment]
In your files list, the TIL predictions have a numeric hash at the end that indicates time of download. In theory (aka, non-testing formats) the file names in `results-tils` and `results-tumors` should be identical. **I will update the error message to be more informative.**

**Comment by lthealy** [comment]
didn't mean to close with commit, wrong verbiage including "Fixed"

**Comment by kaczmarj** [comment]
it is fixed now! thank you.

**Comment by kaczmarj** [comment]
bash script is ready at 

https://github.com/kaczmarj/tumor-til-survival-analysis/blob/main/run-v1.sh

it is run like this:

```bash
bash run-v1.sh data/results-tumor/ data/results-tils/ output
```

given a `data` directory with the following contents

```
data/
├── results-tils
│   ├── prediction-TCGA-3C-AALI-01Z-00-DX1
│   ├── prediction-TCGA-3C-AALJ-01Z-00-DX1
│   ├── prediction-TCGA-3C-AALK-01Z-00-DX1
│   └── prediction-TCGA-4H-AAAK-01Z-00-DX1
└── results-tumor
    ├── prediction-TCGA-3C-AALI-01Z-00-DX1
    ├── prediction-TCGA-3C-AALJ-01Z-00-DX1
    ├── prediction-TCGA-3C-AALK-01Z-00-DX1
    └── prediction-TCGA-4H-AAAK-01Z-00-DX1
```
