### ISSUE TITLE
consider renaming the censor column

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/til_align#15]
the name of the censor column `censorA.0yes.1no` confuses me and i wonder if it will confuse other users. can we simplify it to "event_occurred"  or "deceased" ?

Also why does survival and censor have the A suffix?

**Comment by lthealy** [comment]
Can definitely rename, this is just the naming convention we use in the Moffitt lab. The suffix A is appended in case there are multiple endpoints. We can iteratively generate survival associations for different clinical endpoints (as yet not supported)
