### ISSUE TITLE
setwd to /data will error if /data is not available

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/til_align#2]
can we remove this line? we can set the working directory ourselves when we run the container.

https://github.com/SBU-BMI/til_align/blob/f14c0b3d7fb136a62cbd3521bb44661a5fb01974/scripts_and_docker/commandLineAlign.R#L11

**Comment by lthealy** [comment]
currently this script moves into a mounted volume when the container is created, so /data will necessarily exist by nature of the code being called. Can definitely be deleted with updated implementation approach though which seems to be the plan.

Will keep for now so we handle implementation all at once
