### ISSUE TITLE
BUG: error when running commandLineAlign.R from command line

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/til_align#3]
in the docker image i get an error when i run 

```
root@33e9392a4247:/code# commandLineAlign.R 
/usr/bin/env: ‘Rscript --vanilla’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

the error is due to this line.

https://github.com/SBU-BMI/til_align/blob/f14c0b3d7fb136a62cbd3521bb44661a5fb01974/scripts_and_docker/commandLineAlign.R#L1

a fix would be to use

```
#!/usr/bin/env -S Rscript --vanilla
```

or 

```
#!/usr/bin/env Rscript
```

`renderWrapper.R` has the same issue

https://github.com/SBU-BMI/til_align/blob/f14c0b3d7fb136a62cbd3521bb44661a5fb01974/scripts_and_docker/renderWrapper.R#L1

**Comment by lthealy** [comment]
Any preference between the two fix formats?

**Comment by kaczmarj** [comment]
we probably want to use the `--vanilla` option so let's go with 

```bash
#!/usr/bin/env -S Rscript --vanilla
```
